steps:
- task: UseDotNet@2
  displayName: 'Use .NET 9.x SDK'
  inputs:
    version: '9.x'

- script: 'dotnet --version'
  displayName: 'Check dotnet version'

- task: DotNetCoreCLI@2
  displayName: 'Build primary source'
  inputs:
    workingDirectory: $(Solution.MainDirectory)
    command: 'build'
